name: "setup ssh"
description: "设置分支和pnpm开发环境"
inputs:
    private_key:
        description: ssh 私钥
        required: true
runs:
    using: "composite"
    steps:
        - shell: bash
          name: set private key
          run: |
              mkdir -p ~/.ssh/
              echo "${{ inputs.private_key }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
