name: ci test
on:
    workflow_dispatch:
        inputs:
            job:
                description: 任务名称
                required: false
                type: string

jobs:
    env_only:
        if: ${{ inputs.job == 'env_only' }}
        runs-on: ubuntu-latest
        steps:
            - uses: asnow-c/template@v1
              with:
                  nodev: 20
                  pnpmv: 8
            - run: ls
    pnpm_install:
        if: ${{ inputs.job == 'pnpm_install' }}
        runs-on: ubuntu-latest
        steps:
            - uses: asnow-c/template@v1
              with:
                  nodev: 20
                  pnpmv: 8
                  run_install: true
            - run: ls
